### ISSUE TITLE
SSH2 broken in PHP 7.0.13 and 5.6.28

### ISSUE THREAD

**Issue by acasademont** [gplessis/dotdeb-php-ssh2#1]
Hi @gplessis,

Due to a security update on the parse_url() method (https://bugs.php.net/bug.php?id=73192) the SSH2 is now broken. There's a new SSH2 patch to solve it (https://forum.remirepo.net/viewtopic.php?id=3509), it would be great if you could pull the changes and issue a new version of the extension. Thanks a lot!!

http://git.php.net/?p=pecl/networking/ssh2.git;a=summary

**Comment by gplessis** [comment]
New php7.0-ssh2 packages have been published. Please confirm that it fixes the issue.

**Comment by acasademont** [comment]
all good now, thank you!

**Comment by gplessis** [comment]
I just published another version of the packages. Could you please confirm that there's no regression and that the issue is still fixed?
